# Generated by Django 4.2.26 on 2025-11-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SHIPMENT', 'Shipment'), ('RECEIPT', 'Receipt'), ('WAREHOUSE', 'Warehouse'), ('RETAIL', 'Retail')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_events', to='batches.woolbatch')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
