# Generated by Django 4.2.26 on 2025-11-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('SCOURING', 'Scouring'), ('CARDING', 'Carding'), ('SPINNING', 'Spinning'), ('DYEING', 'Dyeing'), ('WEAVING', 'Weaving'), ('FINISHING', 'Finishing')], max_length=20)),
                ('facility', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_stages', to='batches.woolbatch')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
